version: '3.9'

services: 
  proxy:
    container_name: nginx-proxy
    image: nginx
    ports: 
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  db:
    container_name: database
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment: 
      POSTGRES_PASSWORD: example

  frontend:
    container_name: frontend
    build: ./frontend/
    ports:
      - 5000:5000
    
  backend:
    container_name: backend
    build: ./backend/
    ports:
      - 8080:8080
    environment: 
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    depends_on: 
      - db
    
  redis:
    container_name: redis
    image: redis


