version: '3.9'

services: 
  db:
    container_name: db_29
    image: postgres:13.2-alpine
    restart: unless-stopped
    volumes: 
      - ./datadir:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: example

  frontend:
    container_name: front_29
    build: ./frontend/
    ports:
      - 5000:5000
    
  backend:
    container_name: back_29
    build: ./backend/
    ports:
      - 8080:8080
    environment: 
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PASSWORD=example
    
  redis:
    container_name: redis_29
    image: redis

volumes: 
  datadir:


    