# Image from task 1.12, assuming you have it. 
# If not run "docker build . -t frontend" in ../task1.12 
FROM frontend

RUN REACT_APP_BACKEND_URL=http://localhost:8080 npm run build

CMD serve -s -l 5000 build



